version: '3.9'

services:
  frontend:
    depends_on:
      - backend
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    extra_hosts:
      - "yarnpkg.com:34.141.48.9"
    networks:
      meeting-network:
        ipv4_address: 172.18.0.2

  backend:
    depends_on:
      - db
    build:
      context: backend/
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    networks:
      meeting-network:
        ipv4_address: 172.18.0.3

  db:
    build:
      context: db/
      dockerfile: ./Dockerfile
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "admiN_123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    networks:
      meeting-network:
        ipv4_address: 172.18.0.4


networks:
  meeting-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
